// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.songrequest.domain;

import com.songrequest.domain.RequestList;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RequestList_Roo_Configurable {
    
    declare @type: RequestList: @Configurable;
    
}
