// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.songrequest.domain;

import com.songrequest.domain.SongRequest;

privileged aspect SongRequest_Roo_JavaBean {
    
    public String SongRequest.getSpotifyURI() {
        return this.spotifyURI;
    }
    
    public void SongRequest.setSpotifyURI(String spotifyURI) {
        this.spotifyURI = spotifyURI;
    }
    
}
